# Generated by Django 3.2.2 on 2021-05-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_alter_blogpost_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='blogIdentifier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
