# Generated by Django 3.2.2 on 2021-05-14 13:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0003_alter_blogpost_blogidentifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 14, 13, 12, 31, 609922, tzinfo=utc)),
        ),
    ]
